name: login_flutter_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## -- Icons packages
  line_awesome_flutter: ^2.0.0
  cupertino_icons: ^1.0.2

  google_fonts: ^4.0.3

  ## -- Splash screen
  flutter_native_splash: ^2.2.19

  ## -- State managment
  get: ^4.6.1

  ## -- Onboarding packages
  liquid_swipe: ^3.0.0 
  smooth_page_indicator: ^1.0.0+2

  
  animated_text_kit: ^4.2.2
  flutter_otp_text_field: ^1.1.1

  ## -- Firebase packages
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/main_logo.jpg"

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/splash_images/logo_splash_screen.png
  image_dark: assets/images/splash_images/logo_splash_screen.png


flutter:
  uses-material-design: true
  assets:
  - assets/logo/
  - assets/icons/
  - assets/images/
  - assets/images/splash_images/
  - assets/images/on_boarding_images/
  - assets/images/welcome_images/
  - assets/images/forget_password/
  - assets/images/dashboard/
  - assets/images/profile/
  
  
  


  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
